services:
  db:
    image: postgres:16-alpine
    container_name: student-performance-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:v0.55.x
    container_name: student-performance-metabase
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase.db/metabase.db
    ports:
      - "3000:3000"
    volumes:
      - ./metabase_data:/metabase.db
    depends_on:
      - db
